export const annexFiveVideos = [
  {
    id: 'Annex5Identity',
    file: '01-identidade-area-aplicacao.mp4',
    poster: '01-identidade-area-aplicacao.png',
    section: '5.1-5.2',
    eyebrow: 'Identidade e area de aplicacao',
    title: 'APDA Framework',
    lead: 'Artefatos Pedagogicos Digitais Abertos para transformar documentos pedagogicos em dados anonimizados e interoperaveis.',
    summary: 'Apresenta o nome da solucao, o foco em AEE e as areas do Anexo IV que o APDA atende.',
    accent: '#0b83a5',
    cards: [
      'Educacao especial inclusiva e Atendimento Educacional Especializado.',
      'Gestao educacional, acessibilidade e apoio pedagogico complementar.',
      'Interoperabilidade, inovacao publica digital e reducao de desigualdades.',
    ],
    flowTitle: 'Foco inicial',
    flow: ['AEE', 'Estudos de caso', 'Planos de atendimento', 'Relatorios', 'Planilhas municipais'],
    closing: 'A proposta comeca onde os registros pedagogicos ja existem: na rotina real das redes municipais.',
  },
  {
    id: 'Annex5Sandbox',
    file: '02-sandbox-regulatorio.mp4',
    poster: '02-sandbox-regulatorio.png',
    section: '5.3',
    eyebrow: 'Por que o Sandbox importa',
    title: 'Validacao regulatoria para uma solucao publica',
    lead: 'O Sandbox transforma uma arquitetura promissora em evidencia tecnica supervisionada pelo MEC.',
    summary: 'Explica por que o Sandbox e decisivo para anonimização, evidencia, interoperabilidade e escala.',
    accent: '#1f8a70',
    cards: [
      'Testar anonimização multicamadas sob supervisao tecnica.',
      'Medir a heterogeneidade real dos formatos municipais.',
      'Dialogar com os padroes da EducaDados enquanto eles sao definidos.',
      'Gerar evidencia para escalabilidade estadual e nacional.',
    ],
    flowTitle: 'Cinco ganhos regulatórios',
    flow: ['Privacidade', 'Evidencia', 'EducaDados', 'Escala', 'PBIA'],
    closing: 'Sem Sandbox: solucao tecnica. Com Sandbox: politica publica em teste.',
  },
  {
    id: 'Annex5Trl',
    file: '03-trl-maturidade.mp4',
    poster: '03-trl-maturidade.png',
    section: '5.4',
    eyebrow: 'TRL e maturidade',
    title: 'TRL 4-5: prototipo validado em laboratorio',
    lead: 'O APDA ja possui arquitetura, prototipos locais e schema preliminar, mas ainda precisa de validacao controlada.',
    summary: 'Mostra o estado atual do projeto e o que precisa ser consolidado no Sandbox.',
    accent: '#b8641c',
    cards: [
      'Ja existe: pipeline inicial, modelos GGUF locais, benchmark e schema JSON.',
      'Em evolucao: dataset ouro, avaliacao pedagogica e impacto algoritmico.',
      'No Sandbox: ampliar testes, validar artefatos e documentar metricas e salvaguardas.',
    ],
    flowTitle: 'Caminho de maturidade',
    flow: ['Conceito', 'Pipeline', 'Prototipo', 'Validacao', 'Evidencia'],
    closing: 'O objetivo e sair do laboratorio com evidencia robusta para uso publico supervisionado.',
  },
  {
    id: 'Annex5Architecture',
    file: '04-arquitetura-apda.mp4',
    poster: '04-arquitetura-apda.png',
    section: '5.5',
    eyebrow: 'Arquitetura APDA',
    title: 'Um pipeline modular para documentos heterogeneos',
    lead: 'A arquitetura trata a variacao municipal como condicao de operacao, nao como excecao.',
    summary: 'Resume os oito modulos arquiteturais e o diferencial de compreender esquemas implicitos.',
    accent: '#0b83a5',
    cards: [
      'Ingestao multiformato: Word, Excel, PDF, imagens e combinacoes.',
      'Extracao estrutural: cores, bordas, celulas mescladas, cabecalhos e hierarquia.',
      'Inferencia APDA: identifica artefatos, campos e limites sem depender do formato local.',
      'Anonimizacao, destilacao, fine-tuning, validacao, auditoria e onboarding municipal.',
    ],
    flowTitle: 'Fluxo tecnico',
    flow: ['Ingestao', 'Extracao', 'Anonimizacao', 'Inferencia', 'Validacao', 'WebUI'],
    closing: 'O modulo central e a compreensao de documentos heterogeneos aplicada ao dominio pedagogico brasileiro.',
  },
  {
    id: 'Annex5ObjectivesBenefits',
    file: '05-objetivos-beneficios.mp4',
    poster: '05-objetivos-beneficios.png',
    section: '5.6-5.7',
    eyebrow: 'Objetivos e beneficios',
    title: 'Traduzir conhecimento pedagogico em infraestrutura publica',
    lead: 'O APDA nao substitui o trabalho do AEE: ele le, respeita e traduz registros para formatos processaveis.',
    summary: 'Conecta os objetivos do framework aos beneficios publicos esperados.',
    accent: '#1f8a70',
    cards: [
      'Estruturar registros dispersos em JSON aberto, anonimizado e auditavel.',
      'Tornar municipios e estudantes visiveis para politicas publicas baseadas em dados.',
      'Apoiar conformidade regulatoria, FUNDEB, EducaDados e pesquisa publica.',
      'Preservar soberania tecnologica com codigo aberto e execucao local.',
    ],
    flowTitle: 'Valor publico',
    flow: ['Visibilidade', 'Direitos', 'FUNDEB', 'EducaDados', 'Dataset AEE', 'Soberania'],
    closing: 'A inteligencia pedagogica local passa a existir tambem como evidencia publica estruturada.',
  },
  {
    id: 'Annex5Risks',
    file: '06-riscos-mitigacoes.mp4',
    poster: '06-riscos-mitigacoes.png',
    section: '5.8',
    eyebrow: 'Riscos e mitigacao',
    title: 'Riscos mapeados antes da escala',
    lead: 'A proposta assume riscos reais e define mitigacoes tecnicas, pedagogicas e institucionais desde o desenho.',
    summary: 'Apresenta os seis riscos principais e as respostas previstas.',
    accent: '#b53333',
    cards: [
      'Vazamento de dados sensiveis e reidentificacao indireta.',
      'Alucinacao, campos inventados e mistura semantica entre estudantes.',
      'Vies discriminatorio e uso indevido para decisao automatizada.',
      'Mitigacoes: anonimizar antes, validar schema, revisar humanamente, bloquear alto risco e registrar logs.',
    ],
    flowTitle: 'Barreiras de seguranca',
    flow: ['Anonimizar', 'Generalizar', 'Validar', 'Revisar', 'Bloquear', 'Auditar'],
    closing: 'Toda saida APDA permanece pendente de validacao humana e nao produz decisao final sobre estudantes.',
  },
  {
    id: 'Annex5DataRightsTransparency',
    file: '07-dados-direitos-transparencia.mp4',
    poster: '07-dados-direitos-transparencia.png',
    section: '5.9-5.13',
    eyebrow: 'Dados, direitos e transparencia',
    title: 'Dados anonimizados, finalidade clara e auditoria por desenho',
    lead: 'O dataset final deve ser composto por textos anonimizados, JSONs sem identificacao pessoal, metadados e registros de validacao.',
    summary: 'Resume coleta, tratamento, protecao de direitos, informacao aos titulares e explicabilidade.',
    accent: '#22313a',
    cards: [
      'Fontes preferenciais: ficticias, sinteticas, publicas ou previamente anonimizadas.',
      'Tratamento: ingestao, extracao, anonimizacao, risco, JSON, validacao, revisao e logs.',
      'Direitos: minimizacao, controle de acesso, descarte seguro e proibicao de decisoes automatizadas.',
      'Explicabilidade: schema publico, versoes, metadados, campos ausentes, confianca e revisao humana.',
    ],
    flowTitle: 'Ciclo de governanca',
    flow: ['Coletar', 'Anonimizar', 'Validar', 'Revisar', 'Armazenar', 'Explicar'],
    closing: 'Explicabilidade no APDA e trilha verificavel, nao interpretacao opaca do modelo.',
  },
  {
    id: 'Annex5MetricsBiasTests',
    file: '08-metricas-vies-testes.mp4',
    poster: '08-metricas-vies-testes.png',
    section: '5.14-5.17',
    eyebrow: 'Metricas, vies e testes',
    title: 'Medir qualidade, privacidade e impacto pedagogico',
    lead: 'A avaliacao combina metricas tecnicas, privacidade, fidelidade pedagogica, mitigacao de vies e testes em fases.',
    summary: 'Fecha o pacote com criterios de performance, vies discriminatorio e plano de testes.',
    accent: '#6f5aa8',
    cards: [
      'Tecnicas: JSON valido, aderencia ao schema, campos inventados, tempo e memoria.',
      'Privacidade: vazamentos, risco de reidentificacao, bloqueios e acuracia da anonimização.',
      'Pedagogicas: fidelidade, barreiras, estrategias, separacao de registros e correcao humana.',
      'Testes: laboratorio, dados sinteticos, destilacao, fine-tuning e ambiente controlado.',
    ],
    flowTitle: 'Fases de avaliacao',
    flow: ['Laboratorio', 'Sinteticos', 'Destilacao', 'Fine-tuning', 'Controlado'],
    closing: 'O modelo e inadequado se produzir classificacao indevida, linguagem discriminatoria ou recomendacao automatizada.',
  },
];

export const annexFiveOutputDir = 'documentos/videos/anexo-iv';
